name: continuous-delivery
'on':
  push: null
  pull_request: null
  workflow_dispatch:
    inputs:
      pr_number:
        description: pull request number referenced
        required: false
      prod:
        description: just for test
        required: false
      level:
        description: just for test2
        required: false
jobs:
  comments-and-label:
    name: comments
    if: "always() &&\n(\n  github.event_name == 'pull_request' ||\n  github.event_name\
      \ == 'workflow_dispatch'\n)\n"
    runs-on: ubuntu-latest
    steps:
    - name: display
      run: "echo \"pr_number: ${{github.event.inputs.pr_number}}\"\necho \"prod: ${{github.event.inputs.prod}}\"\
        \necho \"level:  ${{github.event.inputs.level}}\" \n"
    - name: check test level
      id: checkLevel
      if: always()
      run: "echo \"::set-output name=labelsToPR::e2e-run\"\nif [[ ${{ github.event_name\
        \ }} == 'pull_request' ]];\nthen\n  echo \"::set-output name=prNumber::${{github.event.number}}\"\
        \nelif [[ ${{ github.event_name }} == 'workflow_dispatch' ]];\nthen\n  echo\
        \ \"::set-output name=prNumber::${{github.event.inputs.pr_number}}\"\nfi\n"
    - name: checkout
      uses: actions/checkout@v2
    - name: add label
      id: label
      if: always() && steps.checkLevel.outputs.prNumber != ''
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{secrets.TAO_PTO}}
        number: ${{ steps.checkLevel.outputs.prNumber }}
        labels: ${{ steps.checkLevel.outputs.labelsToPR}}
